# Generated by Django 4.1.2 on 2022-11-10 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coachs", "0001_initial"),
        ("players", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("year_of_conquest", models.DateField()),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="coachs.coach",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True, related_name="titles", to="players.player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
