# Generated by Django 4.1.2 on 2022-11-10 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("initial_date", models.DateField()),
                ("end_date", models.DateField()),
                ("award", models.FloatField()),
            ],
        ),
    ]
